x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: 10m
      max-file: "3"

services:
  nominatim-postgres:
    image: postgis/postgis:18-3.6-alpine
    container_name: nominatim-postgres
    hostname: nominatim-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: very_secure_password
      POSTGRES_USER: postgres
      POSTGRES_DB: nominatim
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # PostgreSQL configuration optimized for Nominatim
    command: >
      postgres
      -c shared_buffers=2GB
      -c maintenance_work_mem=10GB
      -c autovacuum_work_mem=2GB
      -c work_mem=50MB
      -c effective_cache_size=24GB
      -c synchronous_commit=off
      -c max_wal_size=2GB
      -c checkpoint_timeout=10min
      -c checkpoint_completion_target=0.9
      -c max_connections=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    <<: *logging
    networks:
      - nominatim-net

  nominatim:
    image: ghcr.io/maxysoft/nominatim-docker:v5.1.0-9b75039
    container_name: nominatim
    hostname: nominatim
    restart: unless-stopped
    shm_size: 1gb
    environment:
      # External database configuration
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: nominatim
      NOMINATIM_PASSWORD: very_secure_password
      POSTGRES_ADMIN_PASSWORD: very_secure_password
      
      # Nominatim configuration
      # see https://github.com/mediagis/nominatim-docker/tree/master/5.1#configuration for more options
      PBF_URL: https://download.geofabrik.de/europe/monaco-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/monaco-updates/
    volumes:
      - nominatim-data:/nominatim
    depends_on:
      nominatim-postgres:
        condition: service_healthy
        restart: true
    <<: *logging
    networks:
      - nominatim-net

  nominatim-varnish:
    image: varnish:8.0.0-alpine
    container_name: nominatim-varnish
    hostname: nominatim-varnish
    restart: unless-stopped
    command: ["-p", "default_ttl=3600", "-p", "default_grace=3600"]
    volumes:
      - ./varnish.vcl:/etc/varnish/default.vcl:ro
    ports:
      - "80:80"
    environment:
      VARNISH_SIZE: 1G
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: 1207959552
        hard: 1207959552
    depends_on:
      - nominatim
    <<: *logging
    networks:
      - nominatim-net

volumes:
  postgres-data:
  nominatim-data:
