version: "3.8"

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: nominatim-postgres
    environment:
      POSTGRES_PASSWORD: very_secure_password
      POSTGRES_USER: postgres
      POSTGRES_DB: nominatim
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:5.1
    ports:
      - "8080:8080"
    environment:
      # External database configuration
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: nominatim
      NOMINATIM_PASSWORD: very_secure_password
      POSTGRES_ADMIN_PASSWORD: very_secure_password
      
      # Nominatim configuration
      # see https://github.com/mediagis/nominatim-docker/tree/master/5.1#configuration for more options
      PBF_URL: https://download.geofabrik.de/europe/monaco-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/monaco-updates/
    volumes:
      - nominatim-data:/nominatim
    depends_on:
      - postgres
    shm_size: 1gb

volumes:
  postgres-data:
  nominatim-data:
