package ctl

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// RenderEnvFile builds the contents of the Nominatim project .env.
//
// The file is regenerated in full on every start rather than patched in place.
// The previous implementation substituted __PLACEHOLDER__ tokens with sed, which
// consumed the placeholders on the first run: on a persisted volume every later
// start silently ignored POSTGRES_HOST, NOMINATIM_PASSWORD, IMPORT_STYLE and the
// replication intervals. Regenerating is idempotent by construction, so the
// container's configuration always matches its environment.
func RenderEnvFile(c *Config) string {
	kv := map[string]string{
		"NOMINATIM_TOKENIZER":                    "icu",
		"NOMINATIM_REPLICATION_URL":              c.ReplicationURL,
		"NOMINATIM_REPLICATION_UPDATE_INTERVAL":  fmt.Sprint(c.ReplicationUpdateInterval),
		"NOMINATIM_REPLICATION_RECHECK_INTERVAL": fmt.Sprint(c.ReplicationRecheckInterval),
		"NOMINATIM_IMPORT_STYLE":                 c.ImportStyle,
		"NOMINATIM_FLATNODE_FILE":                c.FlatnodeFile,
		"NOMINATIM_DATABASE_DSN":                 c.DSN("nominatim", c.NominatimPassword),
		"NOMINATIM_DATABASE_WEBUSER":             c.WebUser,
	}
	if c.TigerEnabled() {
		kv["NOMINATIM_USE_US_TIGER_DATA"] = "yes"
	}

	keys := make([]string, 0, len(kv))
	for k := range kv {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Generated by nominatim-ctl on every container start. Edits are overwritten.\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%s\n", k, kv[k])
	}
	return b.String()
}

// WriteEnvFile renders and writes the project .env with owner-only permissions.
// The file holds a database password in cleartext, so 0600 matters: with the
// old 0644 any process in the container — including a compromised Gunicorn
// worker — could read it, and on a bind mount so could every host user.
func WriteEnvFile(c *Config, uid, gid int) error {
	path := c.EnvFilePath()
	if err := os.WriteFile(path, []byte(RenderEnvFile(c)), 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	// WriteFile applies its mode only when creating, so a volume carrying a
	// 0644 .env from an older image would keep it.
	if err := os.Chmod(path, 0o600); err != nil {
		return fmt.Errorf("chmod %s: %w", path, err)
	}
	if os.Geteuid() == 0 {
		if err := os.Chown(path, uid, gid); err != nil {
			return fmt.Errorf("chown %s: %w", path, err)
		}
	}
	return nil
}
