#! /usr/bin/env python3

# This script sends a HTTP request to a URL and asserts that its JSON
# response contains an empty array.
#
# It retries the HTTP request a number of times.

import json
import sys

from ci_http import get_json

jsn = get_json(sys.argv[1], attempts=8)
print(f"JSON response returned by {sys.argv[1]}:")
print(json.dumps(jsn, indent=2))
assert len(jsn) == 0
print("✅ JSON was an empty array")

